python code/train.py \
--backbone="mmgcn" \
--name=demo6_cl \
--hidden_dim=256 \
--learning_rate=0.0001 \
--dataset="meld" \
--modalities=av \
--batch_size=32 \
--epochs=60 \
--seed=50 \
--drop_rate=0.4 \
--early_stopping=20 \
--encoder_modules=transformer \
--use_cl \
--cl_threshold=0.4 \
--cl_growth=1.7 \